# Artificial Neural Network

Predicting energy output of power plants

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.13.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_excel('Data/Folds5x2_pp.xlsx')
display(dataset.head(), dataset.shape)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

(9568, 5)

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X[0:10])

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]
 [  26.27   59.44 1012.23   58.77]
 [  15.89   43.96 1014.02   75.24]
 [   9.48   44.71 1019.12   66.43]
 [  14.64   45.   1021.78   41.25]
 [  11.74   43.56 1015.14   70.72]]


In [8]:
print(y[0:10])

[463.26 444.37 488.56 446.48 473.9  443.67 467.35 478.42 475.98 477.5 ]


### Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1))

In [11]:
ann.layers

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
# adam optimizer for gradient descent
# mean squared error loss function as this is regression

ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 674us/step - loss: 104250.7500
Epoch 2/100
240/240 [==============================] - 0s 675us/step - loss: 258.6381
Epoch 3/100
240/240 [==============================] - 0s 679us/step - loss: 240.5608
Epoch 4/100
240/240 [==============================] - 0s 667us/step - loss: 233.7388
Epoch 5/100
240/240 [==============================] - 0s 673us/step - loss: 228.0509
Epoch 6/100
240/240 [==============================] - 0s 656us/step - loss: 221.7573
Epoch 7/100
240/240 [==============================] - 0s 677us/step - loss: 214.7985
Epoch 8/100
240/240 [==============================] - 0s 682us/step - loss: 206.9443
Epoch 9/100
240/240 [==============================] - 0s 665us/step - loss: 198.5191
Epoch 10/100
240/240 [==============================] - 0s 665us/step - loss: 188.8369
Epoch 11/100
240/240 [==============================] - 0s 666us/step - loss: 178.8385
Epoch 12/100
240/240 [===========================

240/240 [==============================] - 0s 683us/step - loss: 24.7412
Epoch 97/100
240/240 [==============================] - 0s 660us/step - loss: 24.3870
Epoch 98/100
240/240 [==============================] - 0s 662us/step - loss: 24.9346
Epoch 99/100
240/240 [==============================] - 0s 657us/step - loss: 24.8433
Epoch 100/100
240/240 [==============================] - 0s 663us/step - loss: 24.8760


### Predicting the results of the Test set

In [14]:
y_pred = ann.predict(X_test)

60/60 [==============================] - 0s 534us/step


In [15]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)), 1))

[[433.9  431.23]
 [462.   460.01]
 [467.23 461.14]
 ...
 [473.99 473.26]
 [439.76 438.  ]
 [459.49 463.28]]


Predictions within <1% of actual output